// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broadcastInfokeydefine.proto

#ifndef PROTOBUF_INCLUDED_broadcastInfokeydefine_2eproto
#define PROTOBUF_INCLUDED_broadcastInfokeydefine_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_broadcastInfokeydefine_2eproto 

namespace protobuf_broadcastInfokeydefine_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_broadcastInfokeydefine_2eproto
namespace BroadCastInfoKeyDefine {
}  // namespace BroadCastInfoKeyDefine
namespace BroadCastInfoKeyDefine {

enum BroadcastInfoKey {
  Recorder_Train_In_Out = 0,
  CommonTimeReference = 1,
  Player_Status = 2,
  Player_Group = 3,
  Player_Camera = 4,
  Player_Type = 5,
  Player_Speed = 6,
  Player_Consigne = 7,
  Player_Mode = 8,
  Player_Extend_Playlist = 9,
  Camera_Type = 10,
  Player_Limit_In_Out = 11,
  Player_Loop_Mode = 12,
  Player_Loop_Count = 13,
  Player_Playlist_ID = 14,
  Player_Playlist_Element_ID = 15,
  DVE_Mode = 16,
  DVE_Type = 17,
  DVE_Channel = 18,
  DVE_Num = 19,
  DVE_Den = 20,
  DVE_CutThreshold = 21,
  DVE_Custom_Transparency = 22,
  RTD_Status = 23,
  RTD_Type = 24,
  RTD_Position = 25,
  GFX_Status = 26,
  GFX_Position = 27,
  GFX_Fade_In_Out_Duration = 28,
  GFX_Loop_In_Out = 29,
  GFX_Loop_Count = 30,
  GFX_Preload_Status = 31,
  HealthInfo_Storage_Capacity = 32,
  HealthInfo_Version = 33,
  HealthInfo_Mixer_Status = 34,
  HealthInfo_Network_Bandwidth = 35,
  HealthInfo_GPU_Temperature = 36,
  HealthInfo_AJA_Status = 37,
  HealthInfo_HDD_Status = 38,
  HealthInfo_ASIO_Status = 39,
  HealthInfo_External_TimeCode = 40,
  CustomInfoBroadcast = 41,
  BMR_Setting = 42,
  VuMeter_Live_Mixer_PGM = 43,
  Recorder_Close_Caption = 44,
  Player_Close_Caption = 45,
  CustomInfoNotify = 46,
  Player_AudioPresetId = 47,
  PiP_Status = 48,
  HealthInfo_Server_Memory = 49,
  Cache_ReplayPlayer_HighResVideo = 50,
  Cache_ReplayPlayer_ExternalAudio = 51,
  HealthInfo_ReferenceStatus = 52,
  HealthInfo_SerialNumber = 53,
  HealthInfo_RemainingTimePerCam = 54,
  Film_Effect_Status = 55,
  Tally = 56,
  BroadcastInfoKey_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  BroadcastInfoKey_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool BroadcastInfoKey_IsValid(int value);
const BroadcastInfoKey BroadcastInfoKey_MIN = Recorder_Train_In_Out;
const BroadcastInfoKey BroadcastInfoKey_MAX = Tally;
const int BroadcastInfoKey_ARRAYSIZE = BroadcastInfoKey_MAX + 1;

const ::google::protobuf::EnumDescriptor* BroadcastInfoKey_descriptor();
inline const ::std::string& BroadcastInfoKey_Name(BroadcastInfoKey value) {
  return ::google::protobuf::internal::NameOfEnum(
    BroadcastInfoKey_descriptor(), value);
}
inline bool BroadcastInfoKey_Parse(
    const ::std::string& name, BroadcastInfoKey* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BroadcastInfoKey>(
    BroadcastInfoKey_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace BroadCastInfoKeyDefine

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::BroadCastInfoKeyDefine::BroadcastInfoKey> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::BroadCastInfoKeyDefine::BroadcastInfoKey>() {
  return ::BroadCastInfoKeyDefine::BroadcastInfoKey_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_broadcastInfokeydefine_2eproto
