// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: broadcastInfokeydefine.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace BroadCastInfoKeyDefine {

  /// <summary>Holder for reflection information generated from broadcastInfokeydefine.proto</summary>
  public static partial class BroadcastInfokeydefineReflection {

    #region Descriptor
    /// <summary>File descriptor for broadcastInfokeydefine.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BroadcastInfokeydefineReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chxicm9hZGNhc3RJbmZva2V5ZGVmaW5lLnByb3RvEhZCcm9hZENhc3RJbmZv",
            "S2V5RGVmaW5lKtIKChBCcm9hZGNhc3RJbmZvS2V5EhkKFVJlY29yZGVyX1Ry",
            "YWluX0luX091dBAAEhcKE0NvbW1vblRpbWVSZWZlcmVuY2UQARIRCg1QbGF5",
            "ZXJfU3RhdHVzEAISEAoMUGxheWVyX0dyb3VwEAMSEQoNUGxheWVyX0NhbWVy",
            "YRAEEg8KC1BsYXllcl9UeXBlEAUSEAoMUGxheWVyX1NwZWVkEAYSEwoPUGxh",
            "eWVyX0NvbnNpZ25lEAcSDwoLUGxheWVyX01vZGUQCBIaChZQbGF5ZXJfRXh0",
            "ZW5kX1BsYXlsaXN0EAkSDwoLQ2FtZXJhX1R5cGUQChIXChNQbGF5ZXJfTGlt",
            "aXRfSW5fT3V0EAsSFAoQUGxheWVyX0xvb3BfTW9kZRAMEhUKEVBsYXllcl9M",
            "b29wX0NvdW50EA0SFgoSUGxheWVyX1BsYXlsaXN0X0lEEA4SHgoaUGxheWVy",
            "X1BsYXlsaXN0X0VsZW1lbnRfSUQQDxIMCghEVkVfTW9kZRAQEgwKCERWRV9U",
            "eXBlEBESDwoLRFZFX0NoYW5uZWwQEhILCgdEVkVfTnVtEBMSCwoHRFZFX0Rl",
            "bhAUEhQKEERWRV9DdXRUaHJlc2hvbGQQFRIbChdEVkVfQ3VzdG9tX1RyYW5z",
            "cGFyZW5jeRAWEg4KClJURF9TdGF0dXMQFxIMCghSVERfVHlwZRAYEhAKDFJU",
            "RF9Qb3NpdGlvbhAZEg4KCkdGWF9TdGF0dXMQGhIQCgxHRlhfUG9zaXRpb24Q",
            "GxIcChhHRlhfRmFkZV9Jbl9PdXRfRHVyYXRpb24QHBITCg9HRlhfTG9vcF9J",
            "bl9PdXQQHRISCg5HRlhfTG9vcF9Db3VudBAeEhYKEkdGWF9QcmVsb2FkX1N0",
            "YXR1cxAfEh8KG0hlYWx0aEluZm9fU3RvcmFnZV9DYXBhY2l0eRAgEhYKEkhl",
            "YWx0aEluZm9fVmVyc2lvbhAhEhsKF0hlYWx0aEluZm9fTWl4ZXJfU3RhdHVz",
            "ECISIAocSGVhbHRoSW5mb19OZXR3b3JrX0JhbmR3aWR0aBAjEh4KGkhlYWx0",
            "aEluZm9fR1BVX1RlbXBlcmF0dXJlECQSGQoVSGVhbHRoSW5mb19BSkFfU3Rh",
            "dHVzECUSGQoVSGVhbHRoSW5mb19IRERfU3RhdHVzECYSGgoWSGVhbHRoSW5m",
            "b19BU0lPX1N0YXR1cxAnEiAKHEhlYWx0aEluZm9fRXh0ZXJuYWxfVGltZUNv",
            "ZGUQKBIXChNDdXN0b21JbmZvQnJvYWRjYXN0ECkSDwoLQk1SX1NldHRpbmcQ",
            "KhIaChZWdU1ldGVyX0xpdmVfTWl4ZXJfUEdNECsSGgoWUmVjb3JkZXJfQ2xv",
            "c2VfQ2FwdGlvbhAsEhgKFFBsYXllcl9DbG9zZV9DYXB0aW9uEC0SFAoQQ3Vz",
            "dG9tSW5mb05vdGlmeRAuEhgKFFBsYXllcl9BdWRpb1ByZXNldElkEC8SDgoK",
            "UGlQX1N0YXR1cxAwEhwKGEhlYWx0aEluZm9fU2VydmVyX01lbW9yeRAxEiMK",
            "H0NhY2hlX1JlcGxheVBsYXllcl9IaWdoUmVzVmlkZW8QMhIkCiBDYWNoZV9S",
            "ZXBsYXlQbGF5ZXJfRXh0ZXJuYWxBdWRpbxAzEh4KGkhlYWx0aEluZm9fUmVm",
            "ZXJlbmNlU3RhdHVzEDQSGwoXSGVhbHRoSW5mb19TZXJpYWxOdW1iZXIQNRIi",
            "Ch5IZWFsdGhJbmZvX1JlbWFpbmluZ1RpbWVQZXJDYW0QNhIWChJGaWxtX0Vm",
            "ZmVjdF9TdGF0dXMQNxIJCgVUYWxseRA4YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::BroadCastInfoKeyDefine.BroadcastInfoKey), }, null));
    }
    #endregion

  }
  #region Enums
  public enum BroadcastInfoKey {
    [pbr::OriginalName("Recorder_Train_In_Out")] RecorderTrainInOut = 0,
    [pbr::OriginalName("CommonTimeReference")] CommonTimeReference = 1,
    [pbr::OriginalName("Player_Status")] PlayerStatus = 2,
    [pbr::OriginalName("Player_Group")] PlayerGroup = 3,
    [pbr::OriginalName("Player_Camera")] PlayerCamera = 4,
    [pbr::OriginalName("Player_Type")] PlayerType = 5,
    [pbr::OriginalName("Player_Speed")] PlayerSpeed = 6,
    [pbr::OriginalName("Player_Consigne")] PlayerConsigne = 7,
    [pbr::OriginalName("Player_Mode")] PlayerMode = 8,
    [pbr::OriginalName("Player_Extend_Playlist")] PlayerExtendPlaylist = 9,
    [pbr::OriginalName("Camera_Type")] CameraType = 10,
    [pbr::OriginalName("Player_Limit_In_Out")] PlayerLimitInOut = 11,
    [pbr::OriginalName("Player_Loop_Mode")] PlayerLoopMode = 12,
    [pbr::OriginalName("Player_Loop_Count")] PlayerLoopCount = 13,
    [pbr::OriginalName("Player_Playlist_ID")] PlayerPlaylistId = 14,
    [pbr::OriginalName("Player_Playlist_Element_ID")] PlayerPlaylistElementId = 15,
    [pbr::OriginalName("DVE_Mode")] DveMode = 16,
    [pbr::OriginalName("DVE_Type")] DveType = 17,
    [pbr::OriginalName("DVE_Channel")] DveChannel = 18,
    [pbr::OriginalName("DVE_Num")] DveNum = 19,
    [pbr::OriginalName("DVE_Den")] DveDen = 20,
    [pbr::OriginalName("DVE_CutThreshold")] DveCutThreshold = 21,
    [pbr::OriginalName("DVE_Custom_Transparency")] DveCustomTransparency = 22,
    [pbr::OriginalName("RTD_Status")] RtdStatus = 23,
    [pbr::OriginalName("RTD_Type")] RtdType = 24,
    [pbr::OriginalName("RTD_Position")] RtdPosition = 25,
    [pbr::OriginalName("GFX_Status")] GfxStatus = 26,
    [pbr::OriginalName("GFX_Position")] GfxPosition = 27,
    [pbr::OriginalName("GFX_Fade_In_Out_Duration")] GfxFadeInOutDuration = 28,
    [pbr::OriginalName("GFX_Loop_In_Out")] GfxLoopInOut = 29,
    [pbr::OriginalName("GFX_Loop_Count")] GfxLoopCount = 30,
    [pbr::OriginalName("GFX_Preload_Status")] GfxPreloadStatus = 31,
    [pbr::OriginalName("HealthInfo_Storage_Capacity")] HealthInfoStorageCapacity = 32,
    [pbr::OriginalName("HealthInfo_Version")] HealthInfoVersion = 33,
    [pbr::OriginalName("HealthInfo_Mixer_Status")] HealthInfoMixerStatus = 34,
    [pbr::OriginalName("HealthInfo_Network_Bandwidth")] HealthInfoNetworkBandwidth = 35,
    [pbr::OriginalName("HealthInfo_GPU_Temperature")] HealthInfoGpuTemperature = 36,
    [pbr::OriginalName("HealthInfo_AJA_Status")] HealthInfoAjaStatus = 37,
    [pbr::OriginalName("HealthInfo_HDD_Status")] HealthInfoHddStatus = 38,
    [pbr::OriginalName("HealthInfo_ASIO_Status")] HealthInfoAsioStatus = 39,
    [pbr::OriginalName("HealthInfo_External_TimeCode")] HealthInfoExternalTimeCode = 40,
    [pbr::OriginalName("CustomInfoBroadcast")] CustomInfoBroadcast = 41,
    [pbr::OriginalName("BMR_Setting")] BmrSetting = 42,
    [pbr::OriginalName("VuMeter_Live_Mixer_PGM")] VuMeterLiveMixerPgm = 43,
    [pbr::OriginalName("Recorder_Close_Caption")] RecorderCloseCaption = 44,
    [pbr::OriginalName("Player_Close_Caption")] PlayerCloseCaption = 45,
    [pbr::OriginalName("CustomInfoNotify")] CustomInfoNotify = 46,
    [pbr::OriginalName("Player_AudioPresetId")] PlayerAudioPresetId = 47,
    [pbr::OriginalName("PiP_Status")] PiPStatus = 48,
    [pbr::OriginalName("HealthInfo_Server_Memory")] HealthInfoServerMemory = 49,
    [pbr::OriginalName("Cache_ReplayPlayer_HighResVideo")] CacheReplayPlayerHighResVideo = 50,
    [pbr::OriginalName("Cache_ReplayPlayer_ExternalAudio")] CacheReplayPlayerExternalAudio = 51,
    [pbr::OriginalName("HealthInfo_ReferenceStatus")] HealthInfoReferenceStatus = 52,
    [pbr::OriginalName("HealthInfo_SerialNumber")] HealthInfoSerialNumber = 53,
    [pbr::OriginalName("HealthInfo_RemainingTimePerCam")] HealthInfoRemainingTimePerCam = 54,
    [pbr::OriginalName("Film_Effect_Status")] FilmEffectStatus = 55,
    [pbr::OriginalName("Tally")] Tally = 56,
  }

  #endregion

}

#endregion Designer generated code
