// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: broadcast.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GoogleProtoBB {

  /// <summary>Holder for reflection information generated from broadcast.proto</summary>
  public static partial class BroadcastReflection {

    #region Descriptor
    /// <summary>File descriptor for broadcast.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BroadcastReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9icm9hZGNhc3QucHJvdG8SDUdvb2dsZVByb3RvQkIiTwobVmFsdWVfUmVj",
            "b3JkZXJfVHJhaW5fSW5fT3V0Eg0KBWNvdW50GAEgASgNEg8KB3RyYWluSW4Y",
            "AiADKAQSEAoIdHJhaW5PdXQYAyADKAQikQEKE1ZhbHVlX1BsYXllcl9TdGF0",
            "dXMSDQoFY291bnQYASABKA0SQQoKc3RhdHVzSW5mbxgCIAMoCzItLkdvb2ds",
            "ZVByb3RvQkIuVmFsdWVfUGxheWVyX1N0YXR1cy5TdGF0dXNJbmZvGigKClN0",
            "YXR1c0luZm8SCgoCaWQYASABKA0SDgoGc3RhdHVzGAIgASgNIlEKD0Jyb2Fk",
            "Q2FzdEhlYWRlchIsCgNrZXkYASABKA4yHy5Hb29nbGVQcm90b0JCLkJyb2Fk",
            "Y2FzdEluZm9LZXkSEAoIZGF0YVNpemUYAiABKA0ilQEKDUJyb2FkQ2FzdERh",
            "dGESSQoVUmVjb3JkZXJfVHJhaW5fSW5fT3V0GAEgASgLMiouR29vZ2xlUHJv",
            "dG9CQi5WYWx1ZV9SZWNvcmRlcl9UcmFpbl9Jbl9PdXQSOQoNUGxheWVyX1N0",
            "YXR1cxgCIAEoCzIiLkdvb2dsZVByb3RvQkIuVmFsdWVfUGxheWVyX1N0YXR1",
            "cyrSCgoQQnJvYWRjYXN0SW5mb0tleRIZChVSZWNvcmRlcl9UcmFpbl9Jbl9P",
            "dXQQABIXChNDb21tb25UaW1lUmVmZXJlbmNlEAESEQoNUGxheWVyX1N0YXR1",
            "cxACEhAKDFBsYXllcl9Hcm91cBADEhEKDVBsYXllcl9DYW1lcmEQBBIPCgtQ",
            "bGF5ZXJfVHlwZRAFEhAKDFBsYXllcl9TcGVlZBAGEhMKD1BsYXllcl9Db25z",
            "aWduZRAHEg8KC1BsYXllcl9Nb2RlEAgSGgoWUGxheWVyX0V4dGVuZF9QbGF5",
            "bGlzdBAJEg8KC0NhbWVyYV9UeXBlEAoSFwoTUGxheWVyX0xpbWl0X0luX091",
            "dBALEhQKEFBsYXllcl9Mb29wX01vZGUQDBIVChFQbGF5ZXJfTG9vcF9Db3Vu",
            "dBANEhYKElBsYXllcl9QbGF5bGlzdF9JRBAOEh4KGlBsYXllcl9QbGF5bGlz",
            "dF9FbGVtZW50X0lEEA8SDAoIRFZFX01vZGUQEBIMCghEVkVfVHlwZRAREg8K",
            "C0RWRV9DaGFubmVsEBISCwoHRFZFX051bRATEgsKB0RWRV9EZW4QFBIUChBE",
            "VkVfQ3V0VGhyZXNob2xkEBUSGwoXRFZFX0N1c3RvbV9UcmFuc3BhcmVuY3kQ",
            "FhIOCgpSVERfU3RhdHVzEBcSDAoIUlREX1R5cGUQGBIQCgxSVERfUG9zaXRp",
            "b24QGRIOCgpHRlhfU3RhdHVzEBoSEAoMR0ZYX1Bvc2l0aW9uEBsSHAoYR0ZY",
            "X0ZhZGVfSW5fT3V0X0R1cmF0aW9uEBwSEwoPR0ZYX0xvb3BfSW5fT3V0EB0S",
            "EgoOR0ZYX0xvb3BfQ291bnQQHhIWChJHRlhfUHJlbG9hZF9TdGF0dXMQHxIf",
            "ChtIZWFsdGhJbmZvX1N0b3JhZ2VfQ2FwYWNpdHkQIBIWChJIZWFsdGhJbmZv",
            "X1ZlcnNpb24QIRIbChdIZWFsdGhJbmZvX01peGVyX1N0YXR1cxAiEiAKHEhl",
            "YWx0aEluZm9fTmV0d29ya19CYW5kd2lkdGgQIxIeChpIZWFsdGhJbmZvX0dQ",
            "VV9UZW1wZXJhdHVyZRAkEhkKFUhlYWx0aEluZm9fQUpBX1N0YXR1cxAlEhkK",
            "FUhlYWx0aEluZm9fSEREX1N0YXR1cxAmEhoKFkhlYWx0aEluZm9fQVNJT19T",
            "dGF0dXMQJxIgChxIZWFsdGhJbmZvX0V4dGVybmFsX1RpbWVDb2RlECgSFwoT",
            "Q3VzdG9tSW5mb0Jyb2FkY2FzdBApEg8KC0JNUl9TZXR0aW5nECoSGgoWVnVN",
            "ZXRlcl9MaXZlX01peGVyX1BHTRArEhoKFlJlY29yZGVyX0Nsb3NlX0NhcHRp",
            "b24QLBIYChRQbGF5ZXJfQ2xvc2VfQ2FwdGlvbhAtEhQKEEN1c3RvbUluZm9O",
            "b3RpZnkQLhIYChRQbGF5ZXJfQXVkaW9QcmVzZXRJZBAvEg4KClBpUF9TdGF0",
            "dXMQMBIcChhIZWFsdGhJbmZvX1NlcnZlcl9NZW1vcnkQMRIjCh9DYWNoZV9S",
            "ZXBsYXlQbGF5ZXJfSGlnaFJlc1ZpZGVvEDISJAogQ2FjaGVfUmVwbGF5UGxh",
            "eWVyX0V4dGVybmFsQXVkaW8QMxIeChpIZWFsdGhJbmZvX1JlZmVyZW5jZVN0",
            "YXR1cxA0EhsKF0hlYWx0aEluZm9fU2VyaWFsTnVtYmVyEDUSIgoeSGVhbHRo",
            "SW5mb19SZW1haW5pbmdUaW1lUGVyQ2FtEDYSFgoSRmlsbV9FZmZlY3RfU3Rh",
            "dHVzEDcSCQoFVGFsbHkQOGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GoogleProtoBB.BroadcastInfoKey), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GoogleProtoBB.Value_Recorder_Train_In_Out), global::GoogleProtoBB.Value_Recorder_Train_In_Out.Parser, new[]{ "Count", "TrainIn", "TrainOut" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GoogleProtoBB.Value_Player_Status), global::GoogleProtoBB.Value_Player_Status.Parser, new[]{ "Count", "StatusInfo" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::GoogleProtoBB.Value_Player_Status.Types.StatusInfo), global::GoogleProtoBB.Value_Player_Status.Types.StatusInfo.Parser, new[]{ "Id", "Status" }, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::GoogleProtoBB.BroadCastHeader), global::GoogleProtoBB.BroadCastHeader.Parser, new[]{ "Key", "DataSize" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GoogleProtoBB.BroadCastData), global::GoogleProtoBB.BroadCastData.Parser, new[]{ "RecorderTrainInOut", "PlayerStatus" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum BroadcastInfoKey {
    [pbr::OriginalName("Recorder_Train_In_Out")] RecorderTrainInOut = 0,
    [pbr::OriginalName("CommonTimeReference")] CommonTimeReference = 1,
    [pbr::OriginalName("Player_Status")] PlayerStatus = 2,
    [pbr::OriginalName("Player_Group")] PlayerGroup = 3,
    [pbr::OriginalName("Player_Camera")] PlayerCamera = 4,
    [pbr::OriginalName("Player_Type")] PlayerType = 5,
    [pbr::OriginalName("Player_Speed")] PlayerSpeed = 6,
    [pbr::OriginalName("Player_Consigne")] PlayerConsigne = 7,
    [pbr::OriginalName("Player_Mode")] PlayerMode = 8,
    [pbr::OriginalName("Player_Extend_Playlist")] PlayerExtendPlaylist = 9,
    [pbr::OriginalName("Camera_Type")] CameraType = 10,
    [pbr::OriginalName("Player_Limit_In_Out")] PlayerLimitInOut = 11,
    [pbr::OriginalName("Player_Loop_Mode")] PlayerLoopMode = 12,
    [pbr::OriginalName("Player_Loop_Count")] PlayerLoopCount = 13,
    [pbr::OriginalName("Player_Playlist_ID")] PlayerPlaylistId = 14,
    [pbr::OriginalName("Player_Playlist_Element_ID")] PlayerPlaylistElementId = 15,
    [pbr::OriginalName("DVE_Mode")] DveMode = 16,
    [pbr::OriginalName("DVE_Type")] DveType = 17,
    [pbr::OriginalName("DVE_Channel")] DveChannel = 18,
    [pbr::OriginalName("DVE_Num")] DveNum = 19,
    [pbr::OriginalName("DVE_Den")] DveDen = 20,
    [pbr::OriginalName("DVE_CutThreshold")] DveCutThreshold = 21,
    [pbr::OriginalName("DVE_Custom_Transparency")] DveCustomTransparency = 22,
    [pbr::OriginalName("RTD_Status")] RtdStatus = 23,
    [pbr::OriginalName("RTD_Type")] RtdType = 24,
    [pbr::OriginalName("RTD_Position")] RtdPosition = 25,
    [pbr::OriginalName("GFX_Status")] GfxStatus = 26,
    [pbr::OriginalName("GFX_Position")] GfxPosition = 27,
    [pbr::OriginalName("GFX_Fade_In_Out_Duration")] GfxFadeInOutDuration = 28,
    [pbr::OriginalName("GFX_Loop_In_Out")] GfxLoopInOut = 29,
    [pbr::OriginalName("GFX_Loop_Count")] GfxLoopCount = 30,
    [pbr::OriginalName("GFX_Preload_Status")] GfxPreloadStatus = 31,
    [pbr::OriginalName("HealthInfo_Storage_Capacity")] HealthInfoStorageCapacity = 32,
    [pbr::OriginalName("HealthInfo_Version")] HealthInfoVersion = 33,
    [pbr::OriginalName("HealthInfo_Mixer_Status")] HealthInfoMixerStatus = 34,
    [pbr::OriginalName("HealthInfo_Network_Bandwidth")] HealthInfoNetworkBandwidth = 35,
    [pbr::OriginalName("HealthInfo_GPU_Temperature")] HealthInfoGpuTemperature = 36,
    [pbr::OriginalName("HealthInfo_AJA_Status")] HealthInfoAjaStatus = 37,
    [pbr::OriginalName("HealthInfo_HDD_Status")] HealthInfoHddStatus = 38,
    [pbr::OriginalName("HealthInfo_ASIO_Status")] HealthInfoAsioStatus = 39,
    [pbr::OriginalName("HealthInfo_External_TimeCode")] HealthInfoExternalTimeCode = 40,
    [pbr::OriginalName("CustomInfoBroadcast")] CustomInfoBroadcast = 41,
    [pbr::OriginalName("BMR_Setting")] BmrSetting = 42,
    [pbr::OriginalName("VuMeter_Live_Mixer_PGM")] VuMeterLiveMixerPgm = 43,
    [pbr::OriginalName("Recorder_Close_Caption")] RecorderCloseCaption = 44,
    [pbr::OriginalName("Player_Close_Caption")] PlayerCloseCaption = 45,
    [pbr::OriginalName("CustomInfoNotify")] CustomInfoNotify = 46,
    [pbr::OriginalName("Player_AudioPresetId")] PlayerAudioPresetId = 47,
    [pbr::OriginalName("PiP_Status")] PiPStatus = 48,
    [pbr::OriginalName("HealthInfo_Server_Memory")] HealthInfoServerMemory = 49,
    [pbr::OriginalName("Cache_ReplayPlayer_HighResVideo")] CacheReplayPlayerHighResVideo = 50,
    [pbr::OriginalName("Cache_ReplayPlayer_ExternalAudio")] CacheReplayPlayerExternalAudio = 51,
    [pbr::OriginalName("HealthInfo_ReferenceStatus")] HealthInfoReferenceStatus = 52,
    [pbr::OriginalName("HealthInfo_SerialNumber")] HealthInfoSerialNumber = 53,
    [pbr::OriginalName("HealthInfo_RemainingTimePerCam")] HealthInfoRemainingTimePerCam = 54,
    [pbr::OriginalName("Film_Effect_Status")] FilmEffectStatus = 55,
    [pbr::OriginalName("Tally")] Tally = 56,
  }

  #endregion

  #region Messages
  public sealed partial class Value_Recorder_Train_In_Out : pb::IMessage<Value_Recorder_Train_In_Out> {
    private static readonly pb::MessageParser<Value_Recorder_Train_In_Out> _parser = new pb::MessageParser<Value_Recorder_Train_In_Out>(() => new Value_Recorder_Train_In_Out());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Value_Recorder_Train_In_Out> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GoogleProtoBB.BroadcastReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Value_Recorder_Train_In_Out() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Value_Recorder_Train_In_Out(Value_Recorder_Train_In_Out other) : this() {
      count_ = other.count_;
      trainIn_ = other.trainIn_.Clone();
      trainOut_ = other.trainOut_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Value_Recorder_Train_In_Out Clone() {
      return new Value_Recorder_Train_In_Out(this);
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 1;
    private uint count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    /// <summary>Field number for the "trainIn" field.</summary>
    public const int TrainInFieldNumber = 2;
    private static readonly pb::FieldCodec<ulong> _repeated_trainIn_codec
        = pb::FieldCodec.ForUInt64(18);
    private readonly pbc::RepeatedField<ulong> trainIn_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<ulong> TrainIn {
      get { return trainIn_; }
    }

    /// <summary>Field number for the "trainOut" field.</summary>
    public const int TrainOutFieldNumber = 3;
    private static readonly pb::FieldCodec<ulong> _repeated_trainOut_codec
        = pb::FieldCodec.ForUInt64(26);
    private readonly pbc::RepeatedField<ulong> trainOut_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<ulong> TrainOut {
      get { return trainOut_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Value_Recorder_Train_In_Out);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Value_Recorder_Train_In_Out other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Count != other.Count) return false;
      if(!trainIn_.Equals(other.trainIn_)) return false;
      if(!trainOut_.Equals(other.trainOut_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Count != 0) hash ^= Count.GetHashCode();
      hash ^= trainIn_.GetHashCode();
      hash ^= trainOut_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Count != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Count);
      }
      trainIn_.WriteTo(output, _repeated_trainIn_codec);
      trainOut_.WriteTo(output, _repeated_trainOut_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Count);
      }
      size += trainIn_.CalculateSize(_repeated_trainIn_codec);
      size += trainOut_.CalculateSize(_repeated_trainOut_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Value_Recorder_Train_In_Out other) {
      if (other == null) {
        return;
      }
      if (other.Count != 0) {
        Count = other.Count;
      }
      trainIn_.Add(other.trainIn_);
      trainOut_.Add(other.trainOut_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Count = input.ReadUInt32();
            break;
          }
          case 18:
          case 16: {
            trainIn_.AddEntriesFrom(input, _repeated_trainIn_codec);
            break;
          }
          case 26:
          case 24: {
            trainOut_.AddEntriesFrom(input, _repeated_trainOut_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Value_Player_Status : pb::IMessage<Value_Player_Status> {
    private static readonly pb::MessageParser<Value_Player_Status> _parser = new pb::MessageParser<Value_Player_Status>(() => new Value_Player_Status());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Value_Player_Status> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GoogleProtoBB.BroadcastReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Value_Player_Status() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Value_Player_Status(Value_Player_Status other) : this() {
      count_ = other.count_;
      statusInfo_ = other.statusInfo_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Value_Player_Status Clone() {
      return new Value_Player_Status(this);
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 1;
    private uint count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    /// <summary>Field number for the "statusInfo" field.</summary>
    public const int StatusInfoFieldNumber = 2;
    private static readonly pb::FieldCodec<global::GoogleProtoBB.Value_Player_Status.Types.StatusInfo> _repeated_statusInfo_codec
        = pb::FieldCodec.ForMessage(18, global::GoogleProtoBB.Value_Player_Status.Types.StatusInfo.Parser);
    private readonly pbc::RepeatedField<global::GoogleProtoBB.Value_Player_Status.Types.StatusInfo> statusInfo_ = new pbc::RepeatedField<global::GoogleProtoBB.Value_Player_Status.Types.StatusInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::GoogleProtoBB.Value_Player_Status.Types.StatusInfo> StatusInfo {
      get { return statusInfo_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Value_Player_Status);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Value_Player_Status other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Count != other.Count) return false;
      if(!statusInfo_.Equals(other.statusInfo_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Count != 0) hash ^= Count.GetHashCode();
      hash ^= statusInfo_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Count != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Count);
      }
      statusInfo_.WriteTo(output, _repeated_statusInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Count);
      }
      size += statusInfo_.CalculateSize(_repeated_statusInfo_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Value_Player_Status other) {
      if (other == null) {
        return;
      }
      if (other.Count != 0) {
        Count = other.Count;
      }
      statusInfo_.Add(other.statusInfo_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Count = input.ReadUInt32();
            break;
          }
          case 18: {
            statusInfo_.AddEntriesFrom(input, _repeated_statusInfo_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Value_Player_Status message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class StatusInfo : pb::IMessage<StatusInfo> {
        private static readonly pb::MessageParser<StatusInfo> _parser = new pb::MessageParser<StatusInfo>(() => new StatusInfo());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<StatusInfo> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::GoogleProtoBB.Value_Player_Status.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public StatusInfo() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public StatusInfo(StatusInfo other) : this() {
          id_ = other.id_;
          status_ = other.status_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public StatusInfo Clone() {
          return new StatusInfo(this);
        }

        /// <summary>Field number for the "id" field.</summary>
        public const int IdFieldNumber = 1;
        private uint id_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public uint Id {
          get { return id_; }
          set {
            id_ = value;
          }
        }

        /// <summary>Field number for the "status" field.</summary>
        public const int StatusFieldNumber = 2;
        private uint status_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public uint Status {
          get { return status_; }
          set {
            status_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as StatusInfo);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(StatusInfo other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Id != other.Id) return false;
          if (Status != other.Status) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Id != 0) hash ^= Id.GetHashCode();
          if (Status != 0) hash ^= Status.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Id != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(Id);
          }
          if (Status != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(Status);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Id != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
          }
          if (Status != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Status);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(StatusInfo other) {
          if (other == null) {
            return;
          }
          if (other.Id != 0) {
            Id = other.Id;
          }
          if (other.Status != 0) {
            Status = other.Status;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Id = input.ReadUInt32();
                break;
              }
              case 16: {
                Status = input.ReadUInt32();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  public sealed partial class BroadCastHeader : pb::IMessage<BroadCastHeader> {
    private static readonly pb::MessageParser<BroadCastHeader> _parser = new pb::MessageParser<BroadCastHeader>(() => new BroadCastHeader());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BroadCastHeader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GoogleProtoBB.BroadcastReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BroadCastHeader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BroadCastHeader(BroadCastHeader other) : this() {
      key_ = other.key_;
      dataSize_ = other.dataSize_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BroadCastHeader Clone() {
      return new BroadCastHeader(this);
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 1;
    private global::GoogleProtoBB.BroadcastInfoKey key_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GoogleProtoBB.BroadcastInfoKey Key {
      get { return key_; }
      set {
        key_ = value;
      }
    }

    /// <summary>Field number for the "dataSize" field.</summary>
    public const int DataSizeFieldNumber = 2;
    private uint dataSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint DataSize {
      get { return dataSize_; }
      set {
        dataSize_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BroadCastHeader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BroadCastHeader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if (DataSize != other.DataSize) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Key != 0) hash ^= Key.GetHashCode();
      if (DataSize != 0) hash ^= DataSize.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Key != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Key);
      }
      if (DataSize != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(DataSize);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Key != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Key);
      }
      if (DataSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DataSize);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BroadCastHeader other) {
      if (other == null) {
        return;
      }
      if (other.Key != 0) {
        Key = other.Key;
      }
      if (other.DataSize != 0) {
        DataSize = other.DataSize;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            key_ = (global::GoogleProtoBB.BroadcastInfoKey) input.ReadEnum();
            break;
          }
          case 16: {
            DataSize = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class BroadCastData : pb::IMessage<BroadCastData> {
    private static readonly pb::MessageParser<BroadCastData> _parser = new pb::MessageParser<BroadCastData>(() => new BroadCastData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BroadCastData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GoogleProtoBB.BroadcastReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BroadCastData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BroadCastData(BroadCastData other) : this() {
      recorderTrainInOut_ = other.recorderTrainInOut_ != null ? other.recorderTrainInOut_.Clone() : null;
      playerStatus_ = other.playerStatus_ != null ? other.playerStatus_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BroadCastData Clone() {
      return new BroadCastData(this);
    }

    /// <summary>Field number for the "Recorder_Train_In_Out" field.</summary>
    public const int RecorderTrainInOutFieldNumber = 1;
    private global::GoogleProtoBB.Value_Recorder_Train_In_Out recorderTrainInOut_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GoogleProtoBB.Value_Recorder_Train_In_Out RecorderTrainInOut {
      get { return recorderTrainInOut_; }
      set {
        recorderTrainInOut_ = value;
      }
    }

    /// <summary>Field number for the "Player_Status" field.</summary>
    public const int PlayerStatusFieldNumber = 2;
    private global::GoogleProtoBB.Value_Player_Status playerStatus_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GoogleProtoBB.Value_Player_Status PlayerStatus {
      get { return playerStatus_; }
      set {
        playerStatus_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BroadCastData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BroadCastData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(RecorderTrainInOut, other.RecorderTrainInOut)) return false;
      if (!object.Equals(PlayerStatus, other.PlayerStatus)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (recorderTrainInOut_ != null) hash ^= RecorderTrainInOut.GetHashCode();
      if (playerStatus_ != null) hash ^= PlayerStatus.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (recorderTrainInOut_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(RecorderTrainInOut);
      }
      if (playerStatus_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PlayerStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (recorderTrainInOut_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RecorderTrainInOut);
      }
      if (playerStatus_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerStatus);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BroadCastData other) {
      if (other == null) {
        return;
      }
      if (other.recorderTrainInOut_ != null) {
        if (recorderTrainInOut_ == null) {
          recorderTrainInOut_ = new global::GoogleProtoBB.Value_Recorder_Train_In_Out();
        }
        RecorderTrainInOut.MergeFrom(other.RecorderTrainInOut);
      }
      if (other.playerStatus_ != null) {
        if (playerStatus_ == null) {
          playerStatus_ = new global::GoogleProtoBB.Value_Player_Status();
        }
        PlayerStatus.MergeFrom(other.PlayerStatus);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (recorderTrainInOut_ == null) {
              recorderTrainInOut_ = new global::GoogleProtoBB.Value_Recorder_Train_In_Out();
            }
            input.ReadMessage(recorderTrainInOut_);
            break;
          }
          case 18: {
            if (playerStatus_ == null) {
              playerStatus_ = new global::GoogleProtoBB.Value_Player_Status();
            }
            input.ReadMessage(playerStatus_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
